### PR TITLE
feat(*) remove cleanup

### PR DESCRIPTION
**Pull request by eskerda**
Alternative to https://github.com/Kong/gojira/pull/57

Not so sure, but seems to me the problem with orphan processes when creating FIFO could be addressed by waiting for the processess to finish. Worth trying at least // CC: https://github.com/Kong/gojira/pull/39 @ms2008 Can you give this a try?

I tried by running `gojira` with three executable eggs that did nothing, and `jobs -p` returned nothing, but without knowing the details of the executable eggs from enterprise I can't fully reproduce if this solves it.

### CODE REVIEW

**Comment by ms2008** [comment]
@eskerda I gave it a try, but no luck, that would not work.

It is worth noting that the orphan processes issue can only be reproduced with the docker-compose v2 version, docker-compose v1 does not have this problem.

**Comment by eskerda** [comment]
> @eskerda I gave it a try. Although it solves the orphan process problem, it poses another problem:
> 
> ```
> $ gojira-ee shell
> [kong-ee-master:/kong]# 
> [kong-ee-master:/kong]# logout   # When CTRL+D is pressed to exit, it will stay stuck here until CTRL+C is pressed
> ```
> 
> It is worth noting that the orphan processes issue can only be reproduced with the docker-compose v2 version, docker-compose v1 does not have this problem.

argh, did not try an interactive session. Can you try again with the updated version?

An alternative solution is to not use fifos all altogether. At the time it seemed neat, but too much complexity for little performance gain is not worth it.

**Comment by ms2008** [comment]
Unfortunately, this time got stuck here. 

```
$ gojira-ee up
[+] Running 4/4
 ⠿ Network kong-ee-master_gojira     Created               0.0s
 ⠿ Container kong-ee-master-db-1     Started               0.4s
 ⠿ Container kong-ee-master-redis-1  Started               0.4s
 ⠿ Container kong-ee-master-kong-1   Started               0.7s       # got stuck here
```

But after you press CTRL+C to exit, there are also no orphan processes after executing `gojira-ee shell`.

**Comment by eskerda** [comment]
> Unfortunately, this time got stuck here.
> 
> ```
> $ gojira-ee up
> [+] Running 4/4
>  ⠿ Network kong-ee-master_gojira     Created               0.0s
>  ⠿ Container kong-ee-master-db-1     Started               0.4s
>  ⠿ Container kong-ee-master-redis-1  Started               0.4s
>  ⠿ Container kong-ee-master-kong-1   Started               0.7s       # got stuck here
> ```
> 
> But after you press CTRL+C to exit, there are also no orphan processes after executing `gojira-ee shell`.

😞 Then I think I have no alternatives to offer and will close this PR. Any of https://github.com/Kong/gojira/pull/59 and https://github.com/Kong/gojira/pull/57 still relevant

**Pull request closed without merging**
