### PR TITLE
feat(*) expose to random ports

### PR DESCRIPTION
**Pull request by eskerda**
* always expose service ports to a random port
* add a port command shortcut

### CODE REVIEW

**Comment by murillopaula** [comment]
works great for kong-cp but can’t get it to work for kong-dp

```
$ gojira hybrid port@kong-dp --index=1 -t 2.3.2.0 8000
Print the public port for a port binding.
Usage: port [options] [--] SERVICE PRIVATE_PORT
Options:
    --protocol=proto  tcp or udp [default: tcp]
    --index=index     index of the container if there are multiple
                      instances of a service [default: 1]
```

I have 3 dps that’s why I need to pass --index=1

fyi, sometimes it needs to be --index=X but other times it needs to be --index X

e.g. this only works with --index X format, the gojira run: gojira hybrid run@kong-dp --index 1 -t 2.3.2.0, doesn’t work in the --index=X format

**Comment by eskerda** [comment]
@murillopaula added a couple of commits that should fix that issue. Let me know about it, thanks!

**Comment by murillopaula** [comment]
what am I doing wrong?

```
~/gojira$ git pull origin feat/ports
From https://github.com/Kong/gojira
 * branch            feat/ports -> FETCH_HEAD
Updating 4406872..4ee4add
Fast-forward
 README.md      |  9 +++++++--
 docs/manual.md | 41 +++++++++++++++++++++++++----------------
 gojira.sh      | 43 +++++++++++++++++++++++--------------------
 3 files changed, 55 insertions(+), 38 deletions(-)

~/gojira$ gojira hybrid port@kong-dp --index=1 -t 2.3.2.0 8000
Print the public port for a port binding.

Usage: port [options] [--] SERVICE PRIVATE_PORT

Options:
    --protocol=proto  tcp or udp [default: tcp]
    --index=index     index of the container if there are multiple
                      instances of a service [default: 1]
```

**Comment by murillopaula** [comment]
this command hangs on my terminal, i.e., doesn't return anything after ~10 secs
```
~/gojira$ gojira hybrid port@[kong-dp:1] -t 2.3.2.0 8000
...
^CERROR: Aborting.
```

**Comment by murillopaula** [comment]
a-ha, this works:

```
~/gojira$ gojira hybrid port@kong-dp:1 -t 2.3.2.0 8000
0.0.0.0:51255
~/gojira$ gojira hybrid port@kong-dp:2 -t 2.3.2.0 8000
0.0.0.0:51256
~/gojira$ gojira hybrid port@kong-dp:3 -t 2.3.2.0 8000
0.0.0.0:51252
```

probably we should add some example usage for this one?

**Comment by murillopaula** [comment]
this change is just awesome, it solves this other issue before too:

> fyi, sometimes it needs to be --index=X but other times it needs to be --index X
>
> e.g. this only works with --index X format, the gojira run: gojira hybrid run@kong-dp --index 1 -t 2.3.2.0, and it doesn’t work using the --index=X format

**Comment by eskerda** [comment]
@murillopaula cool! thanks for trying it out. I updated the usage to try make it clearer.

**Pull request merged**
